 % Temporal and spatial information of stimuli and trials
function taskconfig=task_setting()

% --------------------------------------
% Color palette
% --------------------------------------

taskconfig.colour.black=[0 0 0];
taskconfig.colour.white=[255 255 255];
taskconfig.colour.dark =[10 10 12];



% --------------------------------------
% Instruction
% --------------------------------------

taskconfig.instruction.en.welcome =           ['Welcome to the study XPLO-Judo\n\n' ...
                                             'Soon you will have time to practice so many TANDOKU-RENSHU exercises.\n'...
                                             'The experimenter will guide you through what you need to do.\n'...
                                             'But first, we will need to calibrate all sensors on your body.\n'...
                                             '...to make sure they work properly\n'];

taskconfig.instruction.de.welcome =           ['Willkommen zur Studie XPLO-Judo\n\n' ...
                                             'Bald hast du Zeit, ganz viele TANDOKU-RENSHU-Situationen auszuführen.\n'...
                                             'Die versuchsleitende Person wird dich bei dem ganzen Prozess begleiten.\n'...
                                             'Aber zuerst müssen wir jedoch alle Sensoren an deinem Körper kalibrieren...\n'...
                                             '...um sicherzustellen, dass sie ordnungsgemäß funktionieren.\n'];

taskconfig.instruction.en.check_eeg =           ['FIRST, EXPERIMENTER WILL CHECK YOUR EEG SIGNAL'];

taskconfig.instruction.en.check_motion =           ['YOUR TASK: MOTION & SHOES Calibration\n\n' ...
                                             '1. Starting postion = Keep N-Pose\n'...
                                             '2. Walk = Walk and swing arm'];

taskconfig.instruction.en.check_force =           ['Experimenter turns on the bluetooth on your feet now\n\n'...
                                             'YOUR TASK: \n\n' ...
                                             '1. Listen to the instruction of the experimenter\n'...
                                             '2. Zero = Lift your foot off the ground'];

taskconfig.instruction.en.check_eye=           ['Experimenter connects the phone and eye-tracker now\n\n'...
                                             'YOUR TASK: \n\n' ...
                                             'Stare at the circle\n'...
                                             '--->>> O <<<---\n\n'...
                                             'Experimenter calibrates on the phone so that gaze is at the right position.\n'...
                                             'When done, put phone into the pocket. Help participant wear Gi and belt.'];

taskconfig.instruction.en.eyetracking =           [
                                             'YOUR TASK: Eye Tracking Calibration\n\n' ...
                                             'You will see a circle moving around the screen\n'...
                                             '1. Do not move your head\n'...
                                             '2. Do not try to predict where the dot goes\n\n'...
                                             '3. Follow the circle with your eyes'];

taskconfig.instruction.de.eyetracking =    ['DEINE AUFGABE: Eye-Tracking-Kalibrierung\n\n' ...
                                             'Du wirst einen Kreis sehen, der sich über den Bildschirm bewegt\n'...
                                             '1. Bewege deinen Kopf nicht\n'...
                                             '2. Versuche nicht vorherzusehen, wohin der Punkt wandert\n\n'...
                                             '3. Folge dem Kreis mit deinen Augen'];

taskconfig.instruction.de.check_eeg =       ['ZUERST PRÜFT DIE VERSUCHSLEITUNG DEIN EEG-SIGNAL'];

taskconfig.instruction.de.check_motion =    ['DEINE AUFGABE: KALIBRIERUNG VON BEWEGUNG UND SCHUHEN\n\n' ...
                                             '1. Startposition = N-Pose halten\n'...
                                             '2. Gehen = Gehen und die Arme mitschwingen'];

taskconfig.instruction.de.check_force =     ['Die versuchsleitende Person schaltet jetzt das Bluetooth an deinen Füßen ein\n\n'...
                                             'DEINE AUFGABE:\n\n' ...
                                             '1. Höre auf die Anweisungen der Versuchsleitung\n'...
                                             '2. Nullstellung (Zero) = Hebe deinen Fuß vom Boden ab'];

taskconfig.instruction.de.check_eye =       ['Die versuchsleitende Person verbindet jetzt das Smartphone und den Eye-Tracker\n\n'...
                                             'DEINE AUFGABE:\n\n' ...
                                             'Fixiere den Kreis\n'...
                                             '--->>> O <<<---\n\n'...
                                             'Die Versuchsleitung führt die Kalibrierung auf dem Smartphone durch, damit der Blickpunkt exakt stimmt.\n'...
                                             'Wenn fertig: Smartphone in die Tasche stecken. Der Versuchsperson beim Anziehen von Gi und Gürtel helfen.'];

taskconfig.instruction.en.training =       ['TIME FOR TANDOKU-RENSHU\n\n'...
                                        '(1) Keep N-Pose when you see letter N\n'...
                                        '(2) Only fight when the opponent becomes defensive\n'...
                                        '(3) Execute the technique that you think can best bring the opponent to the ground\n'...
                                        '(4) When finish the move, go back to the start position and wait for the next opponent\n\n'...
                                        'Priority\n'...
                                        '(1) Most plausible technique in each situation\n'...
                                        '(2) Clean execution\n'...
                                        '(3) Quick reaction\n\n'...
                                        'Rules\n'...
                                        '(1) Distribute your strength throughout experiment\n'...
                                        '(2) Do not fall on your back\n'...
                                        '(3) Move within the designated area'...
                                        ];

taskconfig.instruction.de.training =       ['ZEIT FÜR TANDOKU-RENSHU\n\n'...
                                        '(1) Halte die N-Pose, wenn du den Buchstaben N siehst\n'...
                                        '(2) Kämpfe nur, wenn dein Gegner eine defensive Haltung einnimmt\n'...
                                        '(3) Führe die Technik aus, von der du glaubst, dass sie den Gegner am besten zu Boden bringt\n'...
                                        '(4) Gehe nach der Technik zurück in die Startposition und warte auf den nächsten Gegner\n\n'...
                                        'Prioritäten\n'...
                                        '(1) Plausibelste Technik für die jeweilige Situation\n'...
                                        '(2) Saubere Ausführung\n'...
                                        '(3) Schnelle Reaktion\n\n'...
                                        'Regeln\n'...
                                        '(1) Teile deine Kräfte über das gesamte Experiment gut ein\n'...
                                        '(2) Falle nicht auf den Rücken\n'...
                                        '(3) Bewege dich innerhalb des markierten Bereichs'...
                                        ];

taskconfig.instruction.en.heightaffordance =       ['TIME FOR TANDOKU-RENSHU\n\n'...
                                        '(1) Keep N-Pose when you see letter N\n'...
                                        '(2) Only fight when the opponent becomes defensive\n'...
                                        '(3) Execute the technique that you think can best bring the opponent to the ground\n'...
                                        '(4) When finish the move, go back to the start position and wait for the next opponent\n\n'...
                                        'Priority\n'...
                                        '(1) Most plausible technique in each situation\n'...
                                        '(2) Clean execution\n'...
                                        '(3) Quick reaction\n\n'...
                                        'Rules\n'...
                                        '(1) Distribute your strength throughout experiment\n'...
                                        '(2) Do not fall on your back\n'...
                                        '(3) Move within the designated area'...
                                        ];

taskconfig.instruction.de.heightaffordance =       ['ZEIT FÜR TANDOKU-RENSHU\n\n'...
                                        '(1) Halte die N-Pose, wenn du den Buchstaben N siehst\n'...
                                        '(2) Kämpfe nur, wenn dein Gegner eine defensive Haltung einnimmt\n'...
                                        '(3) Führe die Technik aus, von der du glaubst, dass sie den Gegner am besten zu Boden bringt\n'...
                                        '(4) Gehe nach der Technik zurück in die Startposition und warte auf den nächsten Gegner\n\n'...
                                        'Prioritäten\n'...
                                        '(1) Plausibelste Technik für die jeweilige Situation\n'...
                                        '(2) Saubere Ausführung\n'...
                                        '(3) Schnelle Reaktion\n\n'...
                                        'Regeln\n'...
                                        '(1) Teile deine Kräfte über das gesamte Experiment gut ein\n'...
                                        '(2) Falle nicht auf den Rücken\n'...
                                        '(3) Bewege dich innerhalb des markierten Bereichs'...
                                        ];

taskconfig.instruction.estimate = ['YOUR TASK\n\n\n\n ' ...
                                    'Tell us your estimation\n\n' ...
                                    'How TALL were these fighters when standing upright\n\n' ...
                                    '(Feel free to come closer to the screen or use the ruler to give your best estimation)'];



% --------------------------------------
% Timing
% --------------------------------------
taskconfig.numBlocks.training         = 1.00;
taskconfig.numBlocks.heightaffordance = 3.00;
taskconfig.time.offload                    = 3.00; 
taskconfig.time.fixation                   = 0.25; 
taskconfig.time.neutral                    = 0.50; 
taskconfig.time.fight                      = 10.0;
taskconfig.time.iti                        = 0.5; % interstimulus intervall


% --------------------------------------
% Background
% --------------------------------------
taskconfig.bg = taskconfig.colour.dark;


end