 % Temporal and spatial information of stimuli and trials
function taskconfig=task_setting()

% --------------------------------------
% Color palette
% --------------------------------------

taskconfig.colour.black=[0 0 0];
taskconfig.colour.white=[255 255 255];
taskconfig.colour.dark =[10 10 12];



% --------------------------------------
% Instruction
% --------------------------------------

taskconfig.instruction.check_eeg =           ['FIRST, EXPERIMENTER WILL GEL YOUR EEG NOW'];

taskconfig.instruction.check_motion =           ['YOUR TASK: MOTION & SHOES Calibration\n\n' ...
                                             '1. Starting postion = Keep N-Pose\n'...
                                             '2. Walk = Walk and swing arm'];

taskconfig.instruction.check_force =           ['Experimenter turns on the bluetooth on your feet now\n\n'...
                                             'YOUR TASK: \n\n' ...
                                             '1. Listen to the instruction of the experimenter\n'...
                                             '2. Zero = Lift your foot off the ground'];

taskconfig.instruction.check_eye=           ['Experimenter connects the phone and eye-tracker now\n\n'...
                                             'YOUR TASK: \n\n' ...
                                             'Stare at the circle\n'...
                                             '--->>> O <<<---\n\n'...
                                             'Experimenter calibrates on the phone so that gaze is at the right position.\n'...
                                             'When done, put phone into the pocket. Help participant wear Gi and belt.'];

taskconfig.instruction.eyetracking =           [
                                             'YOUR TASK: Eye Tracking Calibration\n\n' ...
                                             '1. Do not move your head\n'...
                                             '2. Only move your eyes\n\n'...
                                             'Keep N-Pose and Follow the circle with your eyes'];

taskconfig.instruction.en.training =       ['TIME FOR TANDOKU-RENSHU\n\n'...
                                        '(1) Keep N-Pose when you see letter N\n'...
                                        '(2) Only fight when the opponent becomes defensive\n'...
                                        '(3) Execute the technique that you think can best bring the opponent to the ground\n'...
                                        '(4) When finish the move, go back to the start position and wait for the next opponent\n\n'...
                                        'Priority\n'...
                                        '(1) Most plausible technique in each situation\n'...
                                        '(2) Clean execution\n'...
                                        '(3) Quick reaction\n\n'...
                                        'Rules\n'...
                                        '(1) Distribute your strength throughout experiment\n'...
                                        '(2) Do not fall on your back\n'...
                                        '(3) Move within the designated area'...
                                        ];

taskconfig.instruction.de.training =       ['TIME FOR TANDOKU-RENSHU\n\n'...
                                        '(1) Keep N-Pose when you see letter N\n'...
                                        '(2) Only fight when the opponent becomes defensive\n'...
                                        '(3) Execute the technique that you think can best bring the opponent to the ground\n'...
                                        '(4) When finish the move, go back to the start position and wait for the next opponent\n\n'...
                                        'Priority\n'...
                                        '(1) Most plausible technique in each situation\n'...
                                        '(2) Clean execution\n'...
                                        '(3) Quick reaction\n\n'...
                                        'Rules\n'...
                                        '(1) Distribute your strength throughout experiment\n'...
                                        '(2) Do not fall on your back\n'...
                                        '(3) Move within the designated area'...
                                        ];


taskconfig.instruction.en.heightaffordance =       ['TIME FOR TANDOKU-RENSHU\n\n'...
                                        '(1) Keep N-Pose when you see letter N\n'...
                                        '(2) Only fight when the opponent becomes defensive\n'...
                                        '(3) Execute the technique that you think can best bring the opponent to the ground\n'...
                                        '(4) When finish the move, go back to the start position and wait for the next opponent\n\n'...
                                        'Priority\n'...
                                        '(1) Most plausible technique in each situation\n'...
                                        '(2) Clean execution\n'...
                                        '(3) Quick reaction\n\n'...
                                        'Rules\n'...
                                        '(1) Distribute your strength throughout experiment\n'...
                                        '(2) Do not fall on your back\n'...
                                        '(3) Move within the designated area'...
                                        ];

taskconfig.instruction.de.heightaffordance =       ['TIME FOR TANDOKU-RENSHU\n\n'...
                                        '(1) Keep N-Pose when you see letter N\n'...
                                        '(2) Only fight when the opponent becomes defensive\n'...
                                        '(3) Execute the technique that you think can best bring the opponent to the ground\n'...
                                        '(4) When finish the move, go back to the start position and wait for the next opponent\n\n'...
                                        'Priority\n'...
                                        '(1) Most plausible technique in each situation\n'...
                                        '(2) Clean execution\n'...
                                        '(3) Quick reaction\n\n'...
                                        'Rules\n'...
                                        '(1) Distribute your strength throughout experiment\n'...
                                        '(2) Do not fall on your back\n'...
                                        '(3) Move within the designated area'...
                                        ];

taskconfig.instruction.estimate = ['YOUR TASK\n\n\n\n ' ...
                                    'Tell us your estimation\n\n' ...
                                    'How TALL were these fighters when standing upright\n\n' ...
                                    '(Feel free to come closer to the screen or use the ruler to give your best estimation)'];



% --------------------------------------
% Timing
% --------------------------------------
taskconfig.numBlocks.training         = 1.00;
taskconfig.numBlocks.heightaffordance = 5.00;
taskconfig.time.offload                    = 5.00; 
taskconfig.time.fixation                   = 0.25; 
taskconfig.time.neutral                    = 0.50; 
taskconfig.time.fight                      = 10.0;
taskconfig.time.iti                        = 0.5; % interstimulus intervall


% --------------------------------------
% Background
% --------------------------------------
taskconfig.bg = taskconfig.colour.dark;


end