%% BIDS Video Slicer, Parallel Matcher, & Color Correction Pipeline
% Description: Select any video inside 'sourcedata'. The script matches the
%              corresponding XDF file, extracts a custom window from 'NPose'
%              until 3 seconds before 'TrialOffset', applies contrast adjustments,
%              and exports BIDS-compliant derivatives into the shared project drive.
clear; clc; close all;


%% 0. Explicit BIDS Paths & Video Selection

fprintf('============ BIDS AUTOMATED TRIAL SLICER ============ \n');
% Define your absolute shared network locations exactly
BASE_LOC        = '\\mpib-berlin.mpg.de\Share\Projects\1223-xplo-judo\private\10_Data\sourcedata';
DERIVATIVES_LOC = '\\mpib-berlin.mpg.de\Share\Projects\1223-xplo-judo\private\10_Data\derivatives';
% Target the pipeline subfolder inside derivatives
PIPELINE_NAME = 'syncdata';
PIPELINE_ROOT = fullfile(DERIVATIVES_LOC, PIPELINE_NAME);
% --- Step 1: Request Video Selection ---
[videoFile, videoPath] = uigetfile({'*.avi;*.mp4;*.mkv', 'Video files (*.avi, *.mp4, *.mkv)'}, ...
                                   'Select a Raw Experiment Video from your sourcedata video folder', ...
                                   BASE_LOC);
if isequal(videoFile, 0)
    error('Execution cancelled. You must select a video file.');
end
% --- Step 2: Extract BIDS Entities via Regular Expression ---
[~, vidName, ~] = fileparts(videoFile);
tokens = regexp(vidName, 'sub-([A-Za-z0-9]+)_ses-([A-Za-z0-9]+)_task-([A-Za-z0-9]+)_run-([0-9]+)_acq-([A-Za-z0-9]+)', 'tokens');
if isempty(tokens)
    error(['Filename Mismatch: The file "%s" does not follow standard BIDS layout. ' ...
           'Ensure it matches the formatting generated by s02_LSL_video-camera.py.'], videoFile);
end
subLabel = tokens{1}{1}; % e.g., "C4TA1N"
sesLabel = tokens{1}{2}; % e.g., "S001"
taskName = tokens{1}{3}; % e.g., "heightaffordance"
runID    = tokens{1}{4}; % e.g., "001"
acqView  = tokens{1}{5}; % e.g., "SideView" or "UpperView"
subID = ['sub-' subLabel];
sesID = ['ses-' sesLabel];

%% 1. Automated BIDS Workspace Validation & Initialization

% Reconstruct absolute source path targets matching your tree layout
LSL_GLOBAL_DIR = fullfile(BASE_LOC, subID, sesID, 'lslglobal');
xdfFileName    = sprintf('%s_%s_task-%s_run-%s_lslglobal.xdf', subID, sesID, taskName, runID);
fullXdfPath    = fullfile(LSL_GLOBAL_DIR, xdfFileName);
% Define absolute output destination folder inside derivatives
OUTPUT_DIR = fullfile(PIPELINE_ROOT, subID, sesID, 'video');
if ~exist(fullXdfPath, 'file')
    error('BIDS Linkage Error: Could not find matching XDF trace file at:\n%s', fullXdfPath);
end
% Ensure the pipeline tree exists
if ~exist(OUTPUT_DIR, 'dir'), mkdir(OUTPUT_DIR); end
% --- Step 3: Automatically Generate required dataset_description.json ---
descJsonPath = fullfile(PIPELINE_ROOT, 'dataset_description.json');
if ~exist(descJsonPath, 'file')
    descStruct = struct(...
        'Name', 'BIDS Video Slicing and Color Correction Pipeline', ...
        'BIDSVersion', '1.11.1', ...
        'DatasetType', 'derivative', ...
        'GeneratedBy', {{struct('Name', 'MATLAB Custom Slicer Script', 'Version', '1.0.0', ...
                        'Description', 'Segments full run videos into discrete trials and applies contrast balancing.')}}, ...
        'SourceDatasets', {{struct('Description', 'Local project workspace raw BIDS baseline tracking')}} ...
    );
    % Write out the JSON ledger formatted beautifully
    fid = fopen(descJsonPath, 'w');
    fprintf(fid, '%s', jsonencode(descStruct, 'PrettyPrint', true));
    fclose(fid);
end
fprintf('\n================ BIDS PIPELINE PATHS ====================\n');
fprintf('Target XDF   : %s\n', fullXdfPath);
fprintf('Export Dest  : %s\n', OUTPUT_DIR);
fprintf('==========================================================\n\n');

%% 2. Load and Parse XDF Streams

fprintf('Loading XDF file streams...\n');
streams = load_xdf(fullXdfPath);
% Find experiment markers stream
mIdx = find(cellfun(@(x) contains(x.info.name, 'Trigger', 'IgnoreCase', true) || ...
                        contains(x.info.name, 'Markers', 'IgnoreCase', true), streams), 1);
% Dynamically target FrameMarker_1 for Side camera, FrameMarker_0 for Upper camera
if contains(acqView, 'Side', 'IgnoreCase', true)
    camIdx = find(cellfun(@(x) strcmp(x.info.name, 'FrameMarker_1'), streams), 1);
else
    camIdx = find(cellfun(@(x) strcmp(x.info.name, 'FrameMarker_0'), streams), 1);
end
if isempty(mIdx) || isempty(camIdx)
    error('Required LSL Marker or FrameMarker stream elements missing inside target XDF.');
end
mText = streams{mIdx}.time_series(:);
mTime = streams{mIdx}.time_stamps(:);
vFrames = streams{camIdx}.time_series(:);
vTime   = streams{camIdx}.time_stamps(:);

%% 3. Reconstruct Trial Segment Timelines (NPose -> TrialOffset - 3s)

trials = struct('trial_id', {}, 'start_ts', {}, 'end_ts', {});
trialCount = 0;
activeTrialStart = [];

% Define lookback reduction duration in seconds
PRE_OFFSET_REDUCTION = 3.0; 

for i = 1:numel(mText)
    if strcmp(mText{i}, 'NPose')
        % Capture the baseline beginning of the window sequence
        activeTrialStart = mTime(i);
        
    elseif contains(mText{i}, 'TrialOffset') && ~isempty(activeTrialStart)
        % Calculate end timestamp (exactly 3 seconds prior to TrialOffset)
        calculatedEnd = mTime(i) - PRE_OFFSET_REDUCTION;
        
        % Check to ensure the window is valid and positive
        if calculatedEnd > activeTrialStart
            trialCount = trialCount + 1;
            trials(trialCount).trial_id = trialCount;
            trials(trialCount).start_ts = activeTrialStart;
            trials(trialCount).end_ts   = calculatedEnd;
        else
            warning('Skipping trial sequence: NPose to TrialOffset duration was shorter than 3 seconds.');
        end
        
        % Reset pointer for the next trial match loop
        activeTrialStart = []; 
    end
end
if trialCount == 0
    error('Zero matches found for target segment timeline requirements: NPose -> (TrialOffset - 3s).');
end
fprintf('Extracted %d trial windows (NPose to TrialOffset - 3s) from sync timeline.\n', trialCount);

%% 4. Cut, Color Correct, and Export Video/JSON Derivatives

reader = VideoReader(fullfile(videoPath, videoFile));
% Establish matrix filters matching your exact FFmpeg config parameters:
% eq=brightness=0.2:contrast=1.3:gamma=1.3
contrastVal   = 1.3;
brightnessVal = 0.2;
gammaExponent = 1 / 1.3; 
for t = 1:trialCount
    % Nearest-neighbor timestamp index mapping
    [~, startFrameIdx] = min(abs(vTime - trials(t).start_ts));
    [~, endFrameIdx]   = min(abs(vTime - trials(t).end_ts));
    
    startFrame = double(vFrames(startFrameIdx));
    endFrame   = double(vFrames(endFrameIdx));
    
    if startFrame < 1, startFrame = 1; end
    if endFrame > reader.NumFrames, endFrame = reader.NumFrames; end
    
    % Strict BIDS derivative syntax containing standard description token: desc-contrasted
    baseOutName = sprintf('%s_%s_task-%s_run-%s_trial-%03d_acq-%s_desc-contrasted_beh', ...
                          subID, sesID, taskName, runID, trials(t).trial_id, acqView);
    outVideoPath = fullfile(OUTPUT_DIR, [baseOutName '.mp4']);
    outSidecarPath = fullfile(OUTPUT_DIR, [baseOutName '.json']);
    
    fprintf(' -> Slicing + Processing Trial %03d/%03d (Frames %d to %d)\n', ...
            t, trialCount, startFrame, endFrame);
        
    % --- Video Frame Stream Export Engine ---
    writer = VideoWriter(outVideoPath, 'MPEG-4');
    writer.FrameRate = reader.FrameRate;
    writer.Quality = 95;
    open(writer);
    
    reader.CurrentTime = (startFrame - 1) / reader.FrameRate;
    currentFrameNum = startFrame;
    
    while hasFrame(reader) && (currentFrameNum <= endFrame)
        imgRaw = readFrame(reader);
        
        % Core Filtering: Native execution mirroring your precise FFmpeg string parameters
        imgDouble = double(imgRaw) / 255.0;
        imgProcessed = (imgDouble - 0.5) * contrastVal + 0.5; % Contrast scaling
        imgProcessed = imgProcessed + brightnessVal;         % Brightness addition
        imgProcessed = imgProcessed .^ gammaExponent;        % Gamma adjustment
        
        % Value clamping to block integer matrix clipping wrappers
        imgProcessed(imgProcessed < 0) = 0;
        imgProcessed(imgProcessed > 1) = 1;
        img = uint8(imgProcessed * 255);
        
        % Burn validation tracking overlay directly onto frame matrix
        lblText = sprintf('Trial: %03d | Frame: %d', trials(t).trial_id, currentFrameNum);
        img = insertText(img, [15, 15], lblText, 'FontSize', 18, ...
                         'TextColor', 'white', 'BoxColor', 'black', 'BoxOpacity', 0.5);
        
        writeVideo(writer, img);
        currentFrameNum = currentFrameNum + 1;
    end
    close(writer);
    
    % --- Step 4: Write Accompanying JSON Sidecar Metadata ---
    sidecar = struct(...
        'SpatialReference', 'Native camera frame space matrix arrays', ...
        'RawSourceFile', videoFile, ...
        'TrialID', trials(t).trial_id, ...
        'StartFrame', startFrame, ...
        'EndFrame', endFrame, ...
        'SegmentSlicingMethod', 'Interval bounded from raw NPose marker timestamp until 3.0 seconds prior to TrialOffset', ...
        'ImageProcessingParameters', struct(...
            'brightness', brightnessVal, ...
            'contrast', contrastVal, ...
            'gamma', 1/gammaExponent ...
        )...
    );
    fid = fopen(outSidecarPath, 'w');
    fprintf(fid, '%s', jsonencode(sidecar, 'PrettyPrint', true));
    fclose(fid);
end

fprintf('\n Batch processing completed successfully. All outputs validated under %s.\n', PIPELINE_ROOT);