%% BIDS Video Slicer, Parallel Matcher, & Frame-LUT Synchronizer Pipeline
% Description: Interactive prompt targets the exact subject/session subdirectory
%              inside 'sourcedata'. The user picks the file instantly, the script
%              matches the XDF file, extracts the trial windows, applies color
%              corrections, and outputs frame-synchronized derivatives to 'syncdata'.
% NOTE: This script has no correction for offset due to beamer and camera

clear; clc; close all;


%% 0. Explicit BIDS Paths & Targeted Subdirectory Navigation

fprintf('============ BIDS AUTOMATED TRIAL SLICER & SYNCHRONIZER ============ \n');
BASE_LOC        = '\\mpib-berlin.mpg.de\Share\Projects\1223-xplo-judo\private\10_Data\sourcedata';
DERIVATIVES_LOC = '\\mpib-berlin.mpg.de\Share\Projects\1223-xplo-judo\private\10_Data\derivatives';

PIPELINE_NAME = 'syncdata';
PIPELINE_ROOT = fullfile(DERIVATIVES_LOC, PIPELINE_NAME);

% --- Step 1: Request Subject & Session via Clean Dialog ---
prompt = {'Enter Subject ID (e.g., C4TA1N):', 'Enter Session ID (e.g., S001):'};
dlgtitle = 'Target Selection';
dims = [1 45];
definput = {'C4TA1N', 'S001'};
userInput = inputdlg(prompt, dlgtitle, dims, definput);

if isempty(userInput)
    error('Execution cancelled by user.');
end

% Standardize labels (strip manual prefixes if entered by mistake)
subLabel = regexprep(userInput{1}, '^sub-', '');
sesLabel = regexprep(userInput{2}, '^ses-', '');
subID = ['sub-' subLabel];
sesID = ['ses-' sesLabel];

% Direct the file dialog to open directly where the raw videos live
TARGET_VID_DIR = fullfile(BASE_LOC, subID, sesID, 'video');

if ~exist(TARGET_VID_DIR, 'dir')
    warning('Target directory not found: %s\nFalling back to BASE_LOC.', TARGET_VID_DIR);
    TARGET_VID_DIR = BASE_LOC;
end

% --- Step 2: Request Video Selection directly from target directory ---
[videoFile, videoPath] = uigetfile({'*.avi;*.mp4;*.mkv', 'Video files (*.avi, *.mp4, *.mkv)'}, ...
                                   ['Select Video for ' subID ' ' sesID], ...
                                   TARGET_VID_DIR);
if isequal(videoFile, 0)
    error('Execution cancelled. You must select a video file.');
end

% --- Step 3: Extract Remaining BIDS Entities via Regular Expression ---
[~, vidName, ~] = fileparts(videoFile);
tokens = regexp(vidName, 'sub-([A-Za-z0-9]+)_ses-([A-Za-z0-9]+)_task-([A-Za-z0-9]+)_run-([0-9]+)_acq-([A-Za-z0-9]+)', 'tokens');
if isempty(tokens)
    error(['Filename Mismatch: The file "%s" does not follow standard BIDS layout. ' ...
           'Ensure it matches formatting generated by s02_LSL_video-camera.py.'], videoFile);
end

taskName = tokens{1}{3}; % e.g., "heightaffordance"
runID    = tokens{1}{4}; % e.g., "001"
acqView  = tokens{1}{5}; % e.g., "SideView" or "UpperView"


%% 1. Automated BIDS Workspace Validation & Initialization

LSL_GLOBAL_DIR = fullfile(BASE_LOC, subID, sesID, 'lslglobal');
xdfFileName    = sprintf('%s_%s_task-%s_run-%s_lslglobal.xdf', subID, sesID, taskName, runID);
fullXdfPath    = fullfile(LSL_GLOBAL_DIR, xdfFileName);

OUTPUT_DIR = fullfile(PIPELINE_ROOT, subID, sesID, 'video');
if ~exist(fullXdfPath, 'file')
    error('BIDS Linkage Error: Could not find matching XDF trace file at:\n%s', fullXdfPath);
end

if ~exist(OUTPUT_DIR, 'dir'), mkdir(OUTPUT_DIR); end

% --- Step 4: Automatically Generate required dataset_description.json ---
descJsonPath = fullfile(PIPELINE_ROOT, 'dataset_description.json');
if ~exist(descJsonPath, 'file')
    descStruct = struct(...
        'Name', 'BIDS Video Slicing and Multi-Modal Synchronization Pipeline', ...
        'BIDSVersion', '1.11.1', ...
        'DatasetType', 'derivative', ...
        'GeneratedBy', {{struct('Name', 'MATLAB Frame-Sync Slicer Script', 'Version', '2.0.0', ...
                        'Description', 'Segments full run videos into discrete trials and outputs frame-by-frame LSL tracking matrices.')}}, ...
        'SourceDatasets', {{struct('Description', 'Local project workspace raw BIDS baseline tracking streams')}} ...
    );
    fid = fopen(descJsonPath, 'w');
    fprintf(fid, '%s', jsonencode(descStruct, 'PrettyPrint', true));
    fclose(fid);
end

fprintf('\n================ BIDS PIPELINE PATHS ====================\n');
fprintf('Target XDF   : %s\n', fullXdfPath);
fprintf('Export Dest  : %s\n', OUTPUT_DIR);
fprintf('==========================================================\n\n');


%% 2. Load and Parse XDF Streams

fprintf('Loading XDF file streams...\n');
streams = load_xdf(fullXdfPath);

mIdx = find(cellfun(@(x) contains(x.info.name, 'Trigger', 'IgnoreCase', true) || ...
                        contains(x.info.name, 'Markers', 'IgnoreCase', true), streams), 1);

if contains(acqView, 'Side', 'IgnoreCase', true)
    camIdx = find(cellfun(@(x) strcmp(x.info.name, 'FrameMarker_1'), streams), 1);
else
    camIdx = find(cellfun(@(x) strcmp(x.info.name, 'FrameMarker_0'), streams), 1);
end

if isempty(mIdx) || isempty(camIdx)
    error('Required LSL Marker or FrameMarker stream elements missing inside target XDF.');
end

mText = streams{mIdx}.time_series(:);
mTime = streams{mIdx}.time_stamps(:);
vFrames = streams{camIdx}.time_series(:);
vTime   = streams{camIdx}.time_stamps(:);


%% 3. Reconstruct Trial Segment Timelines (NPose -> TrialOffset - 3s)

trials = struct('trial_id', {}, 'start_ts', {}, 'end_ts', {});
trialCount = 0;
activeTrialStart = [];
PRE_OFFSET_REDUCTION = 3.0; 

for i = 1:numel(mText)
    if strcmp(mText{i}, 'NPose')
        activeTrialStart = mTime(i);
    elseif contains(mText{i}, 'TrialOffset') && ~isempty(activeTrialStart)
        calculatedEnd = mTime(i) - PRE_OFFSET_REDUCTION;
        if calculatedEnd > activeTrialStart
            trialCount = trialCount + 1;
            trials(trialCount).trial_id = trialCount;
            trials(trialCount).start_ts = activeTrialStart;
            trials(trialCount).end_ts   = calculatedEnd;
        else
            warning('Skipping trial sequence: NPose to TrialOffset duration was shorter than 3 seconds.');
        end
        activeTrialStart = []; 
    end
end
if trialCount == 0
    error('Zero matches found for target segment timeline requirements: NPose -> (TrialOffset - 3s).');
end
fprintf('Extracted %d trial windows from sync timeline.\n', trialCount);


%% 4. Cut, Color Correct, and Export Video, JSON, & TSV Look-Up Tables

reader = VideoReader(fullfile(videoPath, videoFile));

contrastVal   = 1.3;
brightnessVal = 0.2;
gammaExponent = 1 / 1.3; 

for t = 1:trialCount
    [~, startFrameIdx] = min(abs(vTime - trials(t).start_ts));
    [~, endFrameIdx]   = min(abs(vTime - trials(t).end_ts));
    
    startFrame = double(vFrames(startFrameIdx));
    endFrame   = double(vFrames(endFrameIdx));
    
    if startFrame < 1, startFrame = 1; end
    if endFrame > reader.NumFrames, endFrame = reader.NumFrames; end
    
    baseOutName = sprintf('%s_%s_task-%s_run-%s_trial-%03d_acq-%s', ...
                          subID, sesID, taskName, runID, trials(t).trial_id, acqView);
    outVideoPath   = fullfile(OUTPUT_DIR, [baseOutName '_desc-contrasted_beh.mp4']);
    outSidecarPath = fullfile(OUTPUT_DIR, [baseOutName '_desc-contrasted_beh.json']);
    outLutPath     = fullfile(OUTPUT_DIR, [baseOutName '_desc-frameLUT_beh.tsv']);
    
    fprintf(' -> Slicing + Sync Processing Trial %03d/%03d (Frames %d to %d)\n', ...
            t, trialCount, startFrame, endFrame);
        
    writer = VideoWriter(outVideoPath, 'MPEG-4');
    writer.FrameRate = reader.FrameRate;
    writer.Quality = 95;
    open(writer);
    
    reader.CurrentTime = (startFrame - 1) / reader.FrameRate;
    currentFrameNum = startFrame;
    
    totalFramesInTrial = (endFrame - currentFrameNum) + 1;
    frameLUTData = zeros(totalFramesInTrial, 3);
    lutRowIdx = 1;
    
    % Core Fix: Safely locate the first valid LSL sample matching this start frame
    startLslEntryIdx = find(vFrames == currentFrameNum, 1);
    if isempty(startLslEntryIdx)
        [~, startLslEntryIdx] = min(abs(vFrames - currentFrameNum));
    end
    trialStartLSLTimestamp = vTime(startLslEntryIdx);
    
    while hasFrame(reader) && (currentFrameNum <= endFrame)
        imgRaw = readFrame(reader);
        
        % Core Correction: Search for the LSL matrix row index where this frame is logged
        lslEntryIdx = find(vFrames == currentFrameNum, 1);
        if isempty(lslEntryIdx)
            % Fallback safety edge case (dropped frame mapping)
            [~, lslEntryIdx] = min(abs(vFrames - currentFrameNum));
        end
        
        globalLslTimestamp = vTime(lslEntryIdx); 
        elapsedTrialTime   = globalLslTimestamp - trialStartLSLTimestamp;
        
        pythonFrameIdx = lutRowIdx - 1; 
        frameLUTData(lutRowIdx, :) = [pythonFrameIdx, globalLslTimestamp, elapsedTrialTime];
        
        % Core Filtering Matrix
        imgDouble = double(imgRaw) / 255.0;
        imgProcessed = (imgDouble - 0.5) * contrastVal + 0.5;
        imgProcessed = imgProcessed + brightnessVal;
        imgProcessed = imgProcessed .^ gammaExponent;
        
        imgProcessed(imgProcessed < 0) = 0;
        imgProcessed(imgProcessed > 1) = 1;
        img = uint8(imgProcessed * 255);
        
        % Burn validation tracking overlay (Python 0-indexed match)
        lblText = sprintf('Trial: %03d | Frame: %d', trials(t).trial_id, pythonFrameIdx);
        img = insertText(img, [15, 15], lblText, 'FontSize', 18, ...
                         'TextColor', 'white', 'BoxColor', 'black', 'BoxOpacity', 0.5);
        
        writeVideo(writer, img);
        currentFrameNum = currentFrameNum + 1;
        lutRowIdx = lutRowIdx + 1;
    end
    close(writer);
    
    % --- Cleanup Protection: Trim rows if loop exited slightly early ---
    if lutRowIdx <= totalFramesInTrial
        frameLUTData(lutRowIdx:end, :) = [];
    end
    
    % --- Export Synchronized Frame LUT (.tsv) ---
    lutTable = array2table(frameLUTData, 'VariableNames', {'video_frame', 'raw_lsl_timestamp', 'elapsed_trial_time'});
    writetable(lutTable, outLutPath, 'FileType', 'text', 'Delimiter', '\t');
    
    % --- Write Accompanying JSON Sidecar Metadata ---
    sidecar = struct(...
        'SpatialReference', 'Native camera frame space pixel matrix arrays (1280x720)', ...
        'RawSourceFile', videoFile, ...
        'TrialID', trials(t).trial_id, ...
        'FrameRate', reader.FrameRate, ...
        'TargetAnalysisEngine', 'DeepLabCut Pose Estimation', ...
        'TemporalAlignment', struct(...
            'TimeSynchronizedVia', ['LSL FrameMarker_' num2str(contains(acqView, 'Side', 'IgnoreCase', true)) ' Stream'], ...
            'LookupTableFile', [baseOutName '_desc-frameLUT_beh.tsv'], ...
            'StartMarker', 'NPose', ...
            'EndMarker', 'TrialOffset minus 3.0 seconds' ...
        ), ...
        'ImageProcessingParameters', struct(...
            'brightness', brightnessVal, ...
            'contrast', contrastVal, ...
            'gamma', 1/gammaExponent ...
        )...
    );
    fid = fopen(outSidecarPath, 'w');
    fprintf(fid, '%s', jsonencode(sidecar, 'PrettyPrint', true));
    fclose(fid);
end

fprintf('\n Processing complete. Sliced videos and frame-level tracking LUT matrices saved to %s.\n', OUTPUT_DIR);